PRESET_BASE: 'mainnet'
CONFIG_NAME: 'devnet'
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16384
GENESIS_DELAY: 604800
MIN_GENESIS_TIME: 1606824000
GENESIS_FORK_VERSION: 0x20000089
CHURN_LIMIT_QUOTIENT: 65536
SECONDS_PER_SLOT: 12
SLOT_DURATION_MS: 12000
SLOTS_PER_EPOCH: 32
SECONDS_PER_ETH1_BLOCK: 14
ETH1_FOLLOW_DISTANCE: 2048
EPOCHS_PER_ETH1_VOTING_PERIOD: 64
SHARD_COMMITTEE_PERIOD: 256
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 16384
MAX_SEED_LOOKAHEAD: 4
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
MAX_REQUEST_BLOCKS_DENEB: 128
MAX_REQUEST_BLOB_SIDECARS: 768
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: 1152
BLOB_SIDECAR_SUBNET_COUNT: 6
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: 9
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093
ELECTRA_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x20000094
FULU_FORK_EPOCH: 18446744073709551615
FULU_FORK_VERSION: 0x20000095
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6
SUBNETS_PER_NODE: 2
NODE_ID_BITS: 256
MAX_PAYLOAD_SIZE: 10485760
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAX_REQUEST_BLOCKS: 1024
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY:  0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 128000000000
MAX_BLOBS_PER_BLOCK: 6
PROPOSER_REORG_CUTOFF_BPS: 1667
ATTESTATION_DUE_BPS: 3333
AGGREGRATE_DUE_BPS: 6667
SYNC_MESSAGE_DUE_BPS: 3333
CONTRIBUTION_DUE_BPS: 6667
BLOB_SCHEDULE:
  - EPOCH: 412672
    MAX_BLOBS_PER_BLOCK: 15
  - EPOCH: 419072
    MAX_BLOBS_PER_BLOCK: 21