apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  restartPolicy: OnFailure
  containers:
    - name: hello
      image: 'busybox:1.36'
      command:
        - sh
        - '-c'
      args:
        - 'echo ''hello, world'' && sleep 3600'
      volumeMounts: []
  volumes: []
---
apiVersion: v1
kind: Pod
metadata:
  name: el-1
  labels:
    app: el-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: el-1
      image: 'ghcr.io/paradigmxyz/reth:v1.9.3'
      command:
        - /usr/local/bin/reth
      args:
        - node
        - '--chain'
        - /artifacts/genesis.json
        - '--datadir'
        - /data_reth
        - '--color'
        - never
        - '--addr'
        - 0.0.0.0
        - '--port'
        - '30303'
        - '--ipcpath'
        - /data_reth/reth.ipc
        - '--http'
        - '--http.addr'
        - 0.0.0.0
        - '--http.api'
        - 'admin,eth,web3,net,rpc,mev,flashbots'
        - '--http.port'
        - '8545'
        - '--authrpc.port'
        - '8551'
        - '--authrpc.addr'
        - 0.0.0.0
        - '--authrpc.jwtsecret'
        - /artifacts/jwtsecret
        - '--metrics'
        - '0.0.0.0:9090'
        - '--engine.persistence-threshold'
        - '0'
        - '--engine.memory-block-buffer-target'
        - '0'
        - '-vvv'
        - '--disable-discovery'
      ports:
        - name: rpc
          containerPort: 8545
          hostPort: 8545
        - name: authrpc
          containerPort: 8551
          hostPort: 8551
        - name: metrics
          containerPort: 9090
          hostPort: 9090
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: data
          mountPath: /data_reth
  volumes:
    - name: artifacts
      hostPath:
        path: /home/caner/w/decker/artifacts
        type: Directory
    - name: data
      emptyDir: {}
