apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: decker-artifacts
  labels:
    app.kubernetes.io/part-of: decker-l1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 256Mi
