apiVersion: apps/v1
kind: Deployment
metadata:
  name: helix-beacon-1
  labels:
    app.kubernetes.io/name: helix-beacon-1
    app.kubernetes.io/part-of: decker-l1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helix-beacon-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helix-beacon-1
        app.kubernetes.io/part-of: decker-l1
    spec:
      containers:
        - name: helix-beacon-1
          image: 'docker.io/sigp/lighthouse:v8.1.0'
          command:
            - lighthouse
          args:
            - bn
            - '--datadir'
            - /data_beacon
            - '--testnet-dir'
            - /artifacts/testnet
            - '--enable-private-discovery'
            - '--disable-peer-scoring'
            - '--staking'
            - '--enr-address'
            - 127.0.0.1
            - '--enr-udp-port'
            - '19000'
            - '--enr-tcp-port'
            - '19000'
            - '--enr-quic-port'
            - '19100'
            - '--port'
            - '19000'
            - '--quic-port'
            - '19100'
            - '--http'
            - '--http-port'
            - '13500'
            - '--http-address'
            - 0.0.0.0
            - '--http-allow-origin'
            - '*'
            - '--disable-packet-filter'
            - '--target-peers'
            - '5'
            - '--execution-endpoint'
            - 'http://helix-sim-1:18551'
            - '--execution-jwt'
            - /artifacts/jwtsecret
            - '--always-prepare-payload'
            - '--prepare-payload-lookahead'
            - '8000'
            - '--suggested-fee-recipient'
            - '0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990'
            - '--libp2p-addresses'
            - /dns4/beacon-1/tcp/9000
          ports:
            - name: http
              containerPort: 13500
            - name: p2p-tcp
              containerPort: 19000
              protocol: TCP
            - name: p2p-udp
              containerPort: 19000
              protocol: UDP
            - name: quic
              containerPort: 19100
              protocol: UDP
          volumeMounts:
            - name: artifacts
              mountPath: /artifacts
              readOnly: true
            - name: data
              mountPath: /data_beacon
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: decker-artifacts
            readOnly: true
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: helix-beacon-1
  labels:
    app.kubernetes.io/name: helix-beacon-1
    app.kubernetes.io/part-of: decker-l1
spec:
  selector:
    app.kubernetes.io/name: helix-beacon-1
  ports:
    - name: http
      port: 13500
      targetPort: http
