apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-1-config
  labels:
    app.kubernetes.io/part-of: decker-l1
data:
  helix.yml: |
    postgres:
      hostname: 127.0.0.1
      port: 5432
      db_name: postgres
      user: postgres
      region: 0
      region_name: "LOCAL"
    simulators:
      - url: http://helix-sim-1:8555
    beacon_clients:
      - url: http://helix-beacon-1:13500
    relays: []
    builders: []
    validator_preferences:
      filtering: global
      trusted_builders: null
      header_delay: true
    router_config:
      enabled_routes:
        - route: All
    target_get_payload_propagation_duration_ms: 0
    primev_config: null
    discord_webhook_url: null
    alerts_config: null
    inclusion_list: null
    is_submission_instance: true
    is_registration_instance: true
    website:
      enabled: false
    cores:
      auctioneer: 0
      tokio: [0]
      reg_workers: [0]
      tcp_bid_submissions_tile: 0
      decoder: [0]
      simulator: 0
      top_bid: 0
    api_port: 4040
    tcp_port: 4041
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helix-1
  labels:
    app.kubernetes.io/name: helix-1
    app.kubernetes.io/part-of: decker-l1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helix-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helix-1
        app.kubernetes.io/part-of: decker-l1
    spec:
      containers:
        - name: postgres-1
          image: 'docker.io/timescale/timescaledb-ha:pg17'
          env:
            - name: POSTGRES_PASSWORD
              value: helix
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
        - name: helix-1
          image: 'ghcr.io/gattaca-com/helix-relay:main'
          args:
            - '--config'
            - /config/helix.yml
          env:
            - name: RELAY_KEY
              value: '0x64496d4e301e541a6e1237d6ef13a8f8b8b6cb82be9d8ac90073a833dfc2af11'
            - name: ADMIN_TOKEN
              value: decker
            - name: POSTGRES_PASSWORD
              value: helix
          ports:
            - name: http
              containerPort: 4040
            - name: tcp
              containerPort: 4041
            - name: website
              containerPort: 9060
          volumeMounts:
            - name: data
              mountPath: /app/logs
            - name: helix-1-config
              mountPath: /config/helix.yml
              subPath: helix.yml
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: helix-1-config
          configMap:
            name: helix-1-config
---
apiVersion: v1
kind: Service
metadata:
  name: helix-1
  labels:
    app.kubernetes.io/name: helix-1
    app.kubernetes.io/part-of: decker-l1
spec:
  selector:
    app.kubernetes.io/name: helix-1
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
    - name: http
      port: 4040
      targetPort: http
    - name: tcp
      port: 4041
      targetPort: tcp
    - name: website
      port: 9060
      targetPort: website
