apiVersion: apps/v1
kind: Deployment
metadata:
  name: mev-boost-1
  labels:
    app.kubernetes.io/name: mev-boost-1
    app.kubernetes.io/part-of: decker-l1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mev-boost-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mev-boost-1
        app.kubernetes.io/part-of: decker-l1
    spec:
      containers:
        - name: mev-boost-1
          image: 'docker.io/flashbots/mev-boost:latest'
          args:
            - '--addr'
            - '0.0.0.0:18550'
            - '--loglevel'
            - info
            - '--relay'
            - 'http://0xb34cde46f57a246f10dd73ed8714c665dc187b2888353f0b8676c8790e1599de0e96e2a7d515db99126f8d62b7d44ca1@helix-1:4040'
            - '--relay'
            - 'http://0xa1885d66bef164889a2e35845c3b626545d7b0e513efe335e97c3a45e534013fa3bc38c3b7e6143695aecc4872ac52c4@mev-boost-relay-1:9062'
          env:
            - name: GENESIS_FORK_VERSION
              value: '0x20000089'
            - name: GENESIS_TIMESTAMP
              value: '1781014218'
          ports:
            - name: http
              containerPort: 18550
          volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: mev-boost-1
  labels:
    app.kubernetes.io/name: mev-boost-1
    app.kubernetes.io/part-of: decker-l1
spec:
  selector:
    app.kubernetes.io/name: mev-boost-1
  ports:
    - name: http
      port: 18550
      targetPort: http
