apiVersion: v1
kind: ConfigMap
metadata:
  name: rbuilder-1-config
data:
  rbuilder.toml: |
    log_json = false
    log_level = "info,rbuilder=debug"
    redacted_telemetry_server_port = 6061
    redacted_telemetry_server_ip = "0.0.0.0"
    full_telemetry_server_port = 6060
    full_telemetry_server_ip = "0.0.0.0"

    chain = "/artifacts/genesis.json"
    reth_datadir = "/data_reth"
    el_node_ipc_path = "/data_reth/reth.ipc"

    # First prefunded account (0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266)
    coinbase_secret_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    relay_secret_key = "0x25295f0d1d592a90b333e26e85149708208e9f8e8bc18f6c77bd62f8ad7a6866"

    cl_node_url = ["http://beacon-1:3500"]
    genesis_fork_version = "0x20000089"
    jsonrpc_server_port = 8745
    jsonrpc_server_ip = "0.0.0.0"
    extra_data = "rbuilder-1 ⚡"

    ignore_cancellable_orders = true
    root_hash_use_sparse_trie = true
    root_hash_compare_sparse_trie = false
    slot_delta_to_start_bidding_ms = -20000
    live_builders = ["mp-ordering"]
    enabled_relays = ["decker-mev-boost-relay"]

    [[relays]]
    name = "decker-mev-boost-relay"
    url = "http://helix-1:4040"
    use_ssz_for_submit = false
    use_gzip_for_submit = false
    mode = "full"

    [[builders]]
    name = "mp-ordering"
    algo = "ordering-builder"
    discard_txs = true
    sorting = "max-profit"
    failed_order_retries = 1
    drop_failed_orders = true
---
apiVersion: v1
kind: Pod
metadata:
  name: el-1
  labels:
    app: el-1
spec:
  restartPolicy: OnFailure
  shareProcessNamespace: true
  containers:
    - name: el-1
      image: 'ghcr.io/paradigmxyz/reth:v1.9.3'
      command:
        - /usr/local/bin/reth
      args:
        - node
        - '--chain'
        - /artifacts/genesis.json
        - '--datadir'
        - /data_reth
        - '--color'
        - never
        - '--addr'
        - 0.0.0.0
        - '--port'
        - '30303'
        - '--ipcpath'
        - /data_reth/reth.ipc
        - '--http'
        - '--http.addr'
        - 0.0.0.0
        - '--http.api'
        - 'admin,eth,web3,net,rpc,mev,flashbots'
        - '--http.port'
        - '8545'
        - '--authrpc.port'
        - '8551'
        - '--authrpc.addr'
        - 0.0.0.0
        - '--authrpc.jwtsecret'
        - /artifacts/jwtsecret
        - '--metrics'
        - '0.0.0.0:9090'
        - '--engine.persistence-threshold'
        - '0'
        - '--engine.memory-block-buffer-target'
        - '0'
        - '-vvv'
        - '--disable-discovery'
      ports:
        - name: rpc
          containerPort: 8545
          hostPort: 8545
        - name: authrpc
          containerPort: 8551
          hostPort: 8551
        - name: metrics
          containerPort: 9090
          hostPort: 9090
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: el-1-data
          mountPath: /data_reth
    - name: rbuilder-1
      image: 'ghcr.io/flashbots/rbuilder:sha-0f2ea0c'
      args:
        - run
        - /config/rbuilder.toml
      ports:
        - name: http
          containerPort: 8745
          hostPort: 8745
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: el-1-data
          mountPath: /data_reth
        - name: rbuilder-1-config
          mountPath: /config/rbuilder.toml
          subPath: rbuilder.toml
          readOnly: true
  volumes:
    - name: artifacts
      hostPath:
        path: '${DECKER_ROOT}/.runtime/artifacts'
        type: Directory
    - name: el-1-data
      emptyDir: {}
    - name: rbuilder-1-config
      configMap:
        name: rbuilder-1-config
---
apiVersion: v1
kind: Pod
metadata:
  name: beacon-1
  labels:
    app: beacon-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: beacon-1
      image: 'docker.io/sigp/lighthouse:v8.1.0'
      command:
        - lighthouse
      args:
        - bn
        - '--datadir'
        - /data_beacon
        - '--testnet-dir'
        - /artifacts/testnet
        - '--enable-private-discovery'
        - '--disable-peer-scoring'
        - '--staking'
        - '--enr-address'
        - 127.0.0.1
        - '--enr-udp-port'
        - '9000'
        - '--enr-tcp-port'
        - '9000'
        - '--enr-quic-port'
        - '9100'
        - '--port'
        - '9000'
        - '--quic-port'
        - '9100'
        - '--http'
        - '--http-port'
        - '3500'
        - '--http-address'
        - 0.0.0.0
        - '--http-allow-origin'
        - '*'
        - '--disable-packet-filter'
        - '--target-peers'
        - '1'
        - '--execution-endpoint'
        - 'http://el-1:8551'
        - '--execution-jwt'
        - /artifacts/jwtsecret
        - '--always-prepare-payload'
        - '--prepare-payload-lookahead'
        - '8000'
        - '--suggested-fee-recipient'
        - '0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990'
        - '--libp2p-addresses'
        - /dns4/helix-beacon-1/tcp/19000
        - '--builder'
        - 'http://helix-1:4040'
      ports:
        - name: http
          containerPort: 3500
          hostPort: 3500
        - name: p2p-tcp
          containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - name: p2p-udp
          containerPort: 9000
          hostPort: 9000
          protocol: UDP
        - name: quic
          containerPort: 9100
          hostPort: 9100
          protocol: UDP
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: beacon-1-data
          mountPath: /data_beacon
  volumes:
    - name: artifacts
      hostPath:
        path: '${DECKER_ROOT}/.runtime/artifacts'
        type: Directory
    - name: beacon-1-data
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: validator-1
  labels:
    app: validator-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: validator-1
      image: 'docker.io/sigp/lighthouse:v8.1.0'
      command:
        - lighthouse
      args:
        - vc
        - '--datadir'
        - /data_validator
        - '--testnet-dir'
        - /artifacts/testnet
        - '--init-slashing-protection'
        - '--beacon-nodes'
        - 'http://beacon-1:3500'
        - '--suggested-fee-recipient'
        - '0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990'
        - '--builder-proposals'
        - '--prefer-builder-proposals'
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: artifacts
          mountPath: /data_validator
          subPath: data_validator
  volumes:
    - name: artifacts
      hostPath:
        path: '${DECKER_ROOT}/.runtime/artifacts'
        type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-sim-1-config
data:
  collateral.json: |
    {}
---
apiVersion: v1
kind: Pod
metadata:
  name: helix-sim-1
  labels:
    app: helix-sim-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: helix-sim-1
      image: 'ghcr.io/gattaca-com/helix-simulator:main'
      args:
        - node
        - '--chain'
        - /artifacts/genesis.json
        - '--datadir'
        - /data_sim
        - '--color'
        - never
        - '--http'
        - '--http.addr'
        - 0.0.0.0
        - '--http.api'
        - all
        - '--http.port'
        - '8555'
        - '--authrpc.addr'
        - 0.0.0.0
        - '--authrpc.port'
        - '18551'
        - '--authrpc.jwtsecret'
        - /artifacts/jwtsecret
        - '--disable-discovery'
        - '--enable-ext'
        - '--builder-collateral-map-path'
        - /config/collateral.json
        - '--relay-fee-recipient'
        - '0x0000000000000000000000000000000000000000'
        - '--multisend-contract'
        - '0x0000000000000000000000000000000000000000'
      env:
        - name: RELAY_KEY
          value: '0x64496d4e301e541a6e1237d6ef13a8f8b8b6cb82be9d8ac90073a833dfc2af11'
      ports:
        - name: rpc
          containerPort: 8555
          hostPort: 8555
        - name: authrpc
          containerPort: 18551
          hostPort: 18551
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: helix-sim-1-sim-data
          mountPath: /data_sim
        - name: helix-sim-1-config
          mountPath: /config/collateral.json
          subPath: collateral.json
          readOnly: true
  volumes:
    - name: artifacts
      hostPath:
        path: '${DECKER_ROOT}/.runtime/artifacts'
        type: Directory
    - name: helix-sim-1-sim-data
      emptyDir: {}
    - name: helix-sim-1-config
      configMap:
        name: helix-sim-1-config
---
apiVersion: v1
kind: Pod
metadata:
  name: helix-beacon-1
  labels:
    app: helix-beacon-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: helix-beacon-1
      image: 'docker.io/sigp/lighthouse:v8.1.0'
      command:
        - lighthouse
      args:
        - bn
        - '--datadir'
        - /data_beacon
        - '--testnet-dir'
        - /artifacts/testnet
        - '--enable-private-discovery'
        - '--disable-peer-scoring'
        - '--staking'
        - '--enr-address'
        - 127.0.0.1
        - '--enr-udp-port'
        - '19000'
        - '--enr-tcp-port'
        - '19000'
        - '--enr-quic-port'
        - '19100'
        - '--port'
        - '19000'
        - '--quic-port'
        - '19100'
        - '--http'
        - '--http-port'
        - '13500'
        - '--http-address'
        - 0.0.0.0
        - '--http-allow-origin'
        - '*'
        - '--disable-packet-filter'
        - '--target-peers'
        - '1'
        - '--execution-endpoint'
        - 'http://helix-sim-1:18551'
        - '--execution-jwt'
        - /artifacts/jwtsecret
        - '--always-prepare-payload'
        - '--prepare-payload-lookahead'
        - '8000'
        - '--suggested-fee-recipient'
        - '0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990'
        - '--libp2p-addresses'
        - /dns4/beacon-1/tcp/9000
      ports:
        - name: http
          containerPort: 13500
          hostPort: 13500
        - name: p2p-tcp
          containerPort: 19000
          hostPort: 19000
          protocol: TCP
        - name: p2p-udp
          containerPort: 19000
          hostPort: 19000
          protocol: UDP
        - name: quic
          containerPort: 19100
          hostPort: 19100
          protocol: UDP
      volumeMounts:
        - name: artifacts
          mountPath: /artifacts
          readOnly: true
        - name: helix-beacon-1-data
          mountPath: /data_beacon
  volumes:
    - name: artifacts
      hostPath:
        path: '${DECKER_ROOT}/.runtime/artifacts'
        type: Directory
    - name: helix-beacon-1-data
      emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-1-config
data:
  helix.yml: |
    postgres:
      hostname: 127.0.0.1
      port: 5432
      db_name: postgres
      user: postgres
      region: 0
      region_name: "LOCAL"
    simulators:
      - url: http://helix-sim-1:8555
    beacon_clients:
      - url: http://helix-beacon-1:13500
    relays: []
    builders: []
    validator_preferences:
      filtering: global
      trusted_builders: null
      header_delay: true
    router_config:
      enabled_routes:
        - route: All
    target_get_payload_propagation_duration_ms: 0
    primev_config: null
    discord_webhook_url: null
    alerts_config: null
    inclusion_list: null
    is_submission_instance: true
    is_registration_instance: true
    website:
      enabled: false
    cores:
      auctioneer: 0
      tokio: [0]
      reg_workers: [0]
      tcp_bid_submissions_tile: 0
      decoder: [0]
      simulator: 0
      top_bid: 0
    api_port: 4040
    tcp_port: 4041
---
apiVersion: v1
kind: Pod
metadata:
  name: helix-1
  labels:
    app: helix-1
spec:
  restartPolicy: OnFailure
  containers:
    - name: postgres-1
      image: 'docker.io/timescale/timescaledb-ha:pg17'
      env:
        - name: POSTGRES_PASSWORD
          value: helix
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: helix-1-pgdata
          mountPath: /var/lib/postgresql/data
    - name: helix-1
      image: 'ghcr.io/gattaca-com/helix-relay:main'
      args:
        - '--config'
        - /config/helix.yml
      env:
        - name: RELAY_KEY
          value: '0x64496d4e301e541a6e1237d6ef13a8f8b8b6cb82be9d8ac90073a833dfc2af11'
        - name: ADMIN_TOKEN
          value: decker
        - name: POSTGRES_PASSWORD
          value: helix
      ports:
        - name: http
          containerPort: 4040
          hostPort: 4040
        - name: tcp
          containerPort: 4041
          hostPort: 4041
        - name: website
          containerPort: 9060
          hostPort: 9060
      volumeMounts:
        - name: helix-1-relay-logs
          mountPath: /app/logs
        - name: helix-1-config
          mountPath: /config/helix.yml
          subPath: helix.yml
          readOnly: true
  volumes:
    - name: helix-1-pgdata
      emptyDir: {}
    - name: helix-1-relay-logs
      emptyDir: {}
    - name: helix-1-config
      configMap:
        name: helix-1-config
---
apiVersion: v1
kind: Pod
metadata:
  name: dozzle
  labels:
    app: dozzle
spec:
  restartPolicy: OnFailure
  containers:
    - name: dozzle
      image: 'docker.io/amir20/dozzle:latest'
      ports:
        - name: http
          containerPort: 8080
          hostPort: 18080
      volumeMounts:
        - name: podman-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: podman-sock
      hostPath:
        path: /run/user/1000/podman/podman.sock
        type: Socket
